//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMecanicaApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/SysMecanica")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Add", ReplyAction="http://tempuri.org/IProdutoService/AddResponse")]
        void Add(SysMecanicaApp.ServiceReference1.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Add", ReplyAction="http://tempuri.org/IProdutoService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(SysMecanicaApp.ServiceReference1.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Buscar", ReplyAction="http://tempuri.org/IProdutoService/BuscarResponse")]
        SysMecanicaApp.ServiceReference1.Produto Buscar(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Buscar", ReplyAction="http://tempuri.org/IProdutoService/BuscarResponse")]
        System.Threading.Tasks.Task<SysMecanicaApp.ServiceReference1.Produto> BuscarAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoServiceChannel : SysMecanicaApp.ServiceReference1.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<SysMecanicaApp.ServiceReference1.IProdutoService>, SysMecanicaApp.ServiceReference1.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(SysMecanicaApp.ServiceReference1.Produto produto) {
            base.Channel.Add(produto);
        }
        
        public System.Threading.Tasks.Task AddAsync(SysMecanicaApp.ServiceReference1.Produto produto) {
            return base.Channel.AddAsync(produto);
        }
        
        public SysMecanicaApp.ServiceReference1.Produto Buscar(int codigo) {
            return base.Channel.Buscar(codigo);
        }
        
        public System.Threading.Tasks.Task<SysMecanicaApp.ServiceReference1.Produto> BuscarAsync(int codigo) {
            return base.Channel.BuscarAsync(codigo);
        }
    }
}
